name: Test YouTube download

env:
  MY_VIDEO: "https://www.youtube.com/watch?v=19eanlakPn8"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  check:
    name: Check style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.3.2
        poetry config virtualenvs.create false --local
        poetry install
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - name: Test video download
      run: broll yt ${{ env.MY_VIDEO }}
